### ISSUE TITLE
No issue

### ISSUE THREAD

**Issue by Yuki2718** [Yuki2718/adblock#1]
@okiehsch I feel really sorry about this but could you give me a favor? I closed Wilders account but now need to contact a member who seems not to know I have a Github account and what he need is here. I tried to recover my account but no success. Can you point him to this, or take my message? This is the URL: https://www.wilderssecurity.com/threads/ublock-a-lean-and-fast-blocker.365273/page-179#post-2921093

**Comment by okiehsch** [comment]
Why not just register with a new account pm the member and then close the new account?

If that's not possible I can tell the member that you can only be reached here.

**Comment by Yuki2718** [comment]
In fact I registered with a new account but maybe because I did with the same name it's not yet approved and thus can't PM or post or do anything.

**Comment by okiehsch** [comment]
The member is "imdb"?
Private messaging is done by clicking "start a conversation"?

**Comment by Yuki2718** [comment]
Yes for both, IIRC.

**Comment by okiehsch** [comment]
Done.

**Comment by Yuki2718** [comment]
Thanks, truly appreciated!

**Comment by okiehsch** [comment]
No problem, I linked to this issue in my pm, so you should not delete this issue. 😉

**Comment by Yuki2718** [comment]
Really thank you, I feel I need to treat you to a beer. Yeah, I'll keep this issue for a while.

**Comment by geddyhub** [comment]
@okiehsch
hey, thanks for letting me know. 

@Yuki2718 
thanks for redirecting me here. appreciate it. this is just what i was looking for. many thanks for the lists.

**Comment by Yuki2718** [comment]
@geddyhub Which you're looking for? My dynamic rules for uBO on PC is [here](https://github.com/Yuki2718/adblock/blob/master/medium_mode/ublock-dynamic-rules.txt) while uMatrix recipe is [here](https://github.com/uBlockOrigin/uAssets/tree/master/recipes) which usually you don't need to find if you're using uMatrix. Either way click "Raw" button if you prefer plain text page.

**Comment by geddyhub** [comment]
@Yuki2718 
got it, thanks.

**Comment by Yuki2718** [comment]
@geddyhub Could you please contact LowWaterMark at Wilders so that he can close my newly created account? This URL will be an evidence that it's genuinely me and wanting the account to be closed yet I can't even ask him.

**Comment by geddyhub** [comment]
done.

**Comment by Yuki2718** [comment]
@geddyhub Thank you, I'll close this issue but you (and any Wilders friends) can always ask anything to me here : )

**Comment by geddyhub** [comment]
no problem & thank you. take care.
