### ISSUE TITLE
[Question] Cosmetic filter entries

### ISSUE THREAD

**Issue by otksm** [Yuki2718/adblock#10]
Hi. I was recently trying out _Yuki's uBlock Japanese filters_ and noticed some cosmetic filter entries were being collapsed into one single entry e.g.

```css
famitsu.com##.ad-native-campaign, .article-ads-v2, .article-body__contents-pr-primary, .banner-footer-rect-container, .banner-lg-rect-haf-page, .banner-pc, .banner-top-header
```

which IMO made it more difficult to spot duplicate entries between filter lists and My filters in uBO's logger. This also meant I cannot create individual cosmetic filter exceptions (e.g. `famitsu.com#@#.banner-pc`) without first badfiltering the whole entry. 

Given this issue is non-existent on _Adguard Japanese_ (of which the maintainer also contributes towards), may I ask why these entries were organized in this way? Is this some sort of license limitation because some entries seem to be adapted from Tofu filters?

**Comment by Yuki2718** [comment]
Hi, thank you for trying out mine. That is mainly to reduce the file size - beneficial to those who are under limited mobile data usage, which is no more rare nowadays in PC user (yup, almost negligible though) . Also it's more convenient for me to manage except when I search for dead filters. Duplicates with popular lists such as EasyList are made separate to ensure they'll be discarded if used together. AFAIK collapsing or any such slight modification doesn't affect copyright infringement, if any.

I see your problem in the logger and exception. For the moment I'll discompose some filters, and will do more gradually but probably not all.

**Comment by Yuki2718** [comment]
Mostly decomposed, there'll still be some work but allow me to close the issue for now.
