### ISSUE TITLE
topics.nintendo.co.jp

### ISSUE THREAD

**Issue by otksm** [Yuki2718/adblock#11]
### URL(s) where the issue occurs

https://web.archive.org/web/20200927061859/https://topics.nintendo.co.jp/article/3d0de2b7-dfc2-474a-9176-c15ec17c70f0
https://web.archive.org/web/20201028064055/https://topics.nintendo.co.jp/article/3d0de2b7-dfc2-474a-9176-c15ec17c70f0

### Describe the issue

Since October 2020, article content is hidden when javascript is disabled.

### Solution

`topics.nintendo.co.jp##.topics-articleBody > .okra-style-after-init.okra-style-on-init:style(visibility: visible !important)`

**Comment by Yuki2718** [comment]
I can reproduce but this is not an issue of my filters. If I start to fix this kind of issues there'll be plenty of cases. Sorry but won't fix.
