### ISSUE TITLE
jjazz.net

### ISSUE THREAD

**Issue by AirQuick** [Yuki2718/adblock#17]
### URL(s) where the issue occurs (mandatory)

Full URL: 
https://www.jjazz.net/player/?prog_num=J-1627&category=jazz-clock-day
and probably any other programs of the site.

### Describe the issue (mandatory)

Player UI disappears.

### Screenshot(s)

<details><summary>Video:</summary>

https://user-images.githubusercontent.com/8489367/120096914-e3f25080-c168-11eb-8e36-e3e57f5dac10.mp4

</details>

### Versions (mandatory)

- Operating system and version: Windows 10 1903
- Browser and version: MS Edge 90
- uBlock Origin v1.35.2

### Filters (mandatory)

Yuki's uBlock Japanese filters

### Notes

Maybe the player requires something from `adswizz.com`?

**Comment by Yuki2718** [comment]
Fixed, thank you for your report!

**Comment by spirillen** [comment]
Can't reproduce https://github.com/easylist/easylist/pull/7991

![image](https://user-images.githubusercontent.com/44526987/120940137-044b7d80-c71c-11eb-8c40-6738350ad15b.png)

**Comment by Yuki2718** [comment]
@spirillen I can reproduce, note the fix is also in uBlock filters - Unbreak.

**Comment by spirillen** [comment]
I can see that one now, sorry for the disturbance :smiley: 

I'm just confused how the `unbreak`filter got activated!!!
