### ISSUE TITLE
Missing `$`

### ISSUE THREAD

**Issue by spirillen** [Yuki2718/adblock#2]
https://github.com/Yuki2718/adblock/blob/a3fc043f0bda2e6506aa0e597224ae882b6927a9/medium_mode/ublock-anti-whitelist.txt#L5

Not to be a vice ass, but doesn't this line miss the `$` in `$important`

**Comment by spirillen** [comment]
PS: if the first one is true this line would be missing it as well

https://github.com/Yuki2718/adblock/blob/a3fc043f0bda2e6506aa0e597224ae882b6927a9/medium_mode/ublock-anti-whitelist.txt#L13

**Comment by Yuki2718** [comment]
@spirillen Not missing, there should be only one `$` in each line in ABP syntax.

**Comment by spirillen** [comment]
Then I learned that too :+1:
