### ISSUE TITLE
coron.tech

### ISSUE THREAD

**Issue by AirQuick** [Yuki2718/adblock#21]
### URL(s) where the issue occurs (mandatory)

Full URL: 
https://coron.tech/tips/google-photos-unlimited-amazon-photos-prime-unlimited/

### Describe the issue (mandatory)

Blank article body.

### Screenshot(s)

<details><summary>Video:</summary>

https://user-images.githubusercontent.com/8489367/120456126-48631900-c3d0-11eb-921f-1ce88e6a59d4.mp4

</details>

### Versions (mandatory)

- Operating system and version: Windows 10 2004
- Browser and version: MS Edge 90
- uBlock Origin version: v1.35.2

### Filters (mandatory)

Yuki's uBlock Japanese filters

### Notes

I really don't know what the web site in question is all about, but I'm reporting here just in case you might be interested. For my part, even a won't fix is fine.

**Comment by Yuki2718** [comment]
They keep to counter whatever fix I made.

**Comment by hirorpt** [comment]
I know that the website admin had published fake uBOs on AMO in the past. Really malicious against contents-blocking community.
`https://old.reddit.com/r/uBlockOrigin/comments/8818fl/ublock_mobile_appeared_on_amo_claiming_to_be/`
