### ISSUE TITLE
IDoes using AG's URL filter with generic `*$removeparam` creates a performance issue for uBlockOrigin?t's till untokenizable and should never be used on uBO. Hm, AdGuard TPL seems to have

### ISSUE THREAD

**Issue by LennyFox** [Yuki2718/adblock#22]
Changing to AG's `$removeparam` doesn't help, it's till untokenizable and should never be used on uBO.

_Originally posted by @Yuki2718 in https://github.com/Yuki2718/adblock/issues/4#issuecomment-761090777_

**Comment by LennyFox** [comment]
@Yuki2718 

GorHill and you warned that the usage of one badly coded removeparam has the same impact on performance as 10.000 decently coded filter rules. The AdGuard URL filter has over 35 generic removeparam rules, so using your and GorHills rule of thumb using this filter has the same performance impact of a filter with over 350.000 rules?

https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_17_TrackParam/filter.txt

**Comment by Yuki2718** [comment]
All the filters in the list are acceptably good, no idea how you connected specific/generic and good/bad. In fact some domain-specific filters in the list are worse than generic filters<sup>1</sup>, but they're practically limited to their quite unique domain. One just need to understand the way uBO extracts token and how uBO's matching is done. The filters can still be improved from uBO perspective, but then some of them will loose compatibility with AG, which doesn't make sense.

1. Technically all the filters in the list are generic, I'm roughly speaking and meaning `||domain.com^`.
