### ISSUE TITLE
jiji.com

### ISSUE THREAD

**Issue by stm-x** [Yuki2718/adblock#26]
### URL(s) where the issue occurs (mandatory) / 問題のURL（必須）

Full URL / 完全なURL: https://www.jiji.com/jc/d4?p=skm016&d=d4_mili2

### Describe the issue (mandatory) / 何が問題か説明してください（必須）
"ページの先頭へ"ボタンが小見出しにめり込んでしまう
The "Top of Page" button gets stuck in the subheading.

### Screenshot(s) / スクリーンショット

<details><summary>Screenshot:</summary>

![無題](https://user-images.githubusercontent.com/86018494/125050505-f901be00-e0dc-11eb-88b7-62907dbe5cc1.png)

</details>

### Versions (mandatory) / バージョン情報（必須）

- Operating system and version / OSの種類とバージョン: Windows 10 21H1
- Browser and version / ブラウザの種類とバージョン: Edge 91.0.864.64
- AdGuard or uBlock Origin version / AdGuardないしuBlock Originのバージョン: uBlock Origin 1.3.60

### Filters (mandatory) / 使用フィルタ（必須）
Yuki's uBlock Japanese filters

### Notes / その他有用な情報
jiji.com##.Rectangle2 のブロックを解除してやると直るのでこのルールが原因じゃないかなぁと思ってます
似たような現象 (https://github.com/easylist/easylist/pull/8324) が他にもあるので、不具合が起こりやすい？サイトなのかもしれないです
素人判断なので間違ってたらすいません

**Comment by Yuki2718** [comment]
原因はおっしゃる通りです、該当フィルタを調整しました。外してもいいくらいですが。
