### ISSUE TITLE
traicy.com

### ISSUE THREAD

**Issue by otksm** [Yuki2718/adblock#27]
### URL(s) where the issue occurs (mandatory)

https://www.traicy.com

### Describe the issue (mandatory)

`traicy.com##.pc-ad-wide`
A different element is used when viewport width is lower than ~1024px.

### Versions (mandatory)

- Browser and version: Firefox Desktop

### Filters (mandatory)

Adguard Japanese
Yuki's uBlock Japanese filters

### Solution

`traicy.com##.sp-header-ad`

**Comment by Yuki2718** [comment]
As I said in another issue Yuki's uBlock Japanese filters doesn't care about mobile elements, the list is optimized for PC layout and is all about performance - tho non-procedural cosmetic filters won't cause noticeable slowdown, still the fewer to inject, the better. Yet I'll address this case as the site only sees display width and 1024px may be caught in tablet. Nothing so far is determined if Yuki's ublock Japanese filters supports tablet user.

**Comment by Yuki2718** [comment]
BTW subscribing both Adguard Japanese and Yuki's uBlock Japanese filters is waste of resources. The only staff the latter doesn't cover is blogroll which can be covered by either Yuki's uBlock Japanese filters - Annoyances or Yuki's Blogroll filters.

**Comment by otksm** [comment]
> 
> 
> As I said in another issue Yuki's uBlock Japanese filters doesn't care about mobile elements, the list is optimized for PC layout

FWIW this was only caught because I had RFP on at the time which limits viewport width to 1000px when the browser window is not maximized.


> 
> 
> BTW subscribing both Adguard Japanese and Yuki's uBlock Japanese filters is waste of resources. The only staff the latter doesn't cover is blogroll which can be covered by either Yuki's uBlock Japanese filters - Annoyances or Yuki's Blogroll filters.

I do actually subscribe to Yuki's uBlock Japanese filters - Annoyances as well. Adguard Japanese was only mentioned because `traicy.com##.pc-ad-wide` was also on that list.
