### ISSUE TITLE
Rules in solmiru.cl are displayed in error in ubo viewer.

### ISSUE THREAD

**Issue by stm-x** [Yuki2718/adblock#31]
<details><summary>Screenshot:</summary>

![無題](https://user-images.githubusercontent.com/86018494/128830630-d14f535a-40cc-48fe-9703-f034f5955a45.png)

</details>

There seems to be a two-byte character "・" between the separator and the domain, but it doesn't seem to appear in the original txt file.
I'm not sure, but I'll report it.
セパレータとドメインの間に2バイト文字の「・」が表示されているように見えるのですが、原文txtでは表示されないみたいです
よく解らないのですがレポートしておきます

**Comment by Yuki2718** [comment]
編集時に空白文字が入り込んだようです、ご報告ありがとうございます。
