### ISSUE TITLE
aa.com

### ISSUE THREAD

**Issue by zkypfer** [Yuki2718/adblock#32]
### URL(s) where the issue occurs (mandatory) / 問題のURL（必須）

Full URL / 完全なURL: 
https://www.aa.com/* (basically any, at least all that I tried)
https://www.aa.com/homePage.do

### Describe the issue (mandatory) / 何が問題か説明してください（必須）

Breaks the aa.com website. It doesn't display correctly, can't click buttons (e.g., "Log In"). can't close annoying banners and overlay windows...

### Screenshot(s) / スクリーンショット

<details><summary>Screenshot:</summary>

![image](%screenshot_url%)
</details>

### Versions (mandatory) / バージョン情報（必須）

- Operating system and version / OSの種類とバージョン:  Windows 10, most current
- Browser and version / ブラウザの種類とバージョン: Edge 93.0.961.27
- AdGuard or uBlock Origin version / AdGuardないしuBlock Originのバージョン: uBlock 1.37.2

### Filters (mandatory) / 使用フィルタ（必須）

This filter: ||aa.com/fingerprint/
On this filter list: AdGuard Tracking Protection Plus

### Notes / その他有用な情報

This filter corrects 90% of page formatting:
@@||www.aa.com/fingerprint/assets/css/v4/*$stylesheet,domain=www.aa.com

This filter corrects misalignment and random text on the booking window:
@@||www.aa.com/fingerprint/assets/css/v3/*$stylesheet,domain=www.aa.com

This filter removes the "Please enable javascript" banner as well as stops the main/overflow options menu from displaying plain text across the top of the page:
@@||www.aa.com/fingerprint/assets/js/vendor/modernizr*$script,domain=www.aa.com

But...
This filter is preferred to the one above as it allows actually clicking the "Log In" button, closing banners, and closing the in-page pop-up windows:
@@||www.aa.com/fingerprint/assets/js/*$script,domain=www.aa.com

So, after these three filters are enabled to unblock the damaging effects of the original filter list filter, not much is blocked by the original filter (according to the logger only 25% or so, as 75% are being unblocked). Is it even necessary? Am I missing something? I'm very unfamiliar with filters, etc so I'm out of my element. Thanks.

**Comment by Yuki2718** [comment]
@zkypfer Thanks for reporting, only one script under the path is something related to tracking but is not fingerprinting. I removed the filter.
