### ISSUE TITLE
[NSFW] blog.livedoor.jp

### ISSUE THREAD

**Issue by stm-x** [Yuki2718/adblock#35]
### URL(s) where the issue occurs (mandatory) / 問題のURL（必須）

Full URL / 完全なURL: `http://blog.livedoor.jp/satorionechan-koishi/archives/35975934.html#more`

### Describe the issue (mandatory) / 何が問題か説明してください（必須）
The dlsite image embedded in responder number 59 does not show up.
レス番号59に埋め込まれたdlsiteの画像が表示されません。

EDITED: Correct mistakes in the text.
### Screenshot(s) / スクリーンショット

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/86018494/134513987-9aa303a3-9a71-4f2f-a202-98059c62de0b.png)
![image](https://user-images.githubusercontent.com/86018494/134514041-1b6f22b9-6dc6-45c5-b113-db1882e00e0a.png)

</details>

### Versions (mandatory) / バージョン情報（必須）

- Operating system and version / OSの種類とバージョン: Windows 10
- Browser and version / ブラウザの種類とバージョン: MS Edge 93.0.961.52
- AdGuard or uBlock Origin version / AdGuardないしuBlock Originのバージョン: 1.38.0

### Filters (mandatory) / 使用フィルタ（必須）
Yuki's uBlock Japanese filters

### Notes / その他有用な情報

**Comment by Yuki2718** [comment]
ご報告ありがとうございます。ひとまず例外で対処いたしましたが、問題のブロックルール自体の是非を見極めたいためしばらくIssueをopenのままにしておきます。
