### ISSUE TITLE
[removeparam] amazon.co.uk

### ISSUE THREAD

**Issue by otksm** [Yuki2718/adblock#38]
### URL(s) where the issue occurs (mandatory)

Full URL : https://www.amazon[.]co.uk/

### Describe the issue (mandatory)

Probably out of scope but `||amazon.*&smid=$doc,removeparam=smid` does not cover cases such as `https://www.amazon.co.uk/[Product-Name]/dp/[ASIN]?smid=[blahblahblah]`. These were found in the top page under _Top Deals/ Trending Deals/ Lightning Deals_. I was unable to find similar examples in other amazon sites.

### Versions (mandatory)

- Browser and version: Firefox Desktop
- uBlock Origin version: 1.38.6

### Filters (mandatory)

Yuki's uBlock Japanese filters

**Comment by Yuki2718** [comment]
Hi, thank you for the report. I'll fix this.
