### ISSUE TITLE
gu-global.com

### ISSUE THREAD

**Issue by otksm** [Yuki2718/adblock#40]
### URL(s) where the issue occurs (mandatory)

Full URL: https://www.gu-global[.]com/jp/ja/ but also

https://www.gu-global[.]com/cn/
https://www.gu-global[.]com/hk/
https://www.gu-global[.]com/kr/company/
https://www.gu-global[.]com/tw/zh_TW/

### Describe the issue (mandatory)

Canvas fingerprinting. A single `script` GET request followed by three `xhr` POST requests to the same URL. A bunch of data were sent in the request payload under `sensor_data` (including browser UA). Response payload is `{"success": true}`. Probably most obvious when you visit `https://www.gu-global.com/kr/`, of which redirects to an empty page but still decides to fingerprint you anyway.

### Proposed Solution

`/^https?:\/\/www\.gu-global\.com\/(?!(akam\/11\/|cn\/|hk\/|jp\/|kr\/|tw\/))/$script,xmlhttprequest,1p,domain=gu-global.com`

### Versions (mandatory)

- Browser and version: Firefox Desktop
- uBlock Origin version: 1.38.6 

### Filters (mandatory)

Yuki's uBlock Japanese filters

### Notes

URL length and number of forward slashes changes depending on current IP (and date?) so this is the best I can come up with. Blocking the script alone is sufficient for stopping subsequent xhr requests. I also excluded `akam/11/*` because it was already covered by EP and I didn't want to reduce readability in the logger.

**Comment by Yuki2718** [comment]
`/^https?:\/\/www\.gu-global\.com\/(?!(akam\/11\/|cn\/|hk\/|jp\/|kr\/|tw\/))/$script,xmlhttprequest,1p,domain=gu-global.com` This can cause trouble once they opened a new website in another region. How about `/^https:\/\/www\.gu-global\.com\/[0-9a-z]{6,}\/[\/_0-9a-zA-Z]{50,}$/$script,1p,domain=gu-global.com`?

**Comment by otksm** [comment]
> This can cause trouble once they opened a new website in another region

Is there anywhere I can explicitly choose to switch to another region on the website? I can't see any and only arrived at the other regions via Wikipedia and then guesswork.

> Having searched by Wayback machine it seems the length of the first path is always 6

Not really. For example the length of the first path is 12 [here](https://web.archive.org/web/20210708141818/http://www.gu-global.com/jp/ja/) and 8 [here](https://web.archive.org/web/20211109054708/https://www.gu-global.com/jp/ja/). I have seen it as large as 18 but never smaller than 6. Total path length (including forward slashes) can also vary at least between 49-63. Most of the time it ends with a capital `B` but there are definitely exceptions.

**Comment by Yuki2718** [comment]
> Is there anywhere I can explicitly choose to switch to another region on the website?

IDK but it's common merchant to open a new website in long term, so look-ahread regex should be last-resort.

> Not really.

Thank you for investigating far deeper than me. How about
`/^https:\/\/www\.gu-global\.com\/[-0-9a-z]{6,}\/[\/_0-9a-zA-Z]{40,}$/$script,1p,domain=gu-global.com` ?

**Comment by otksm** [comment]
_/^https:\\/\\/www\\.gu-global\\.com\\/[-0-9a-z**A-Z**]{6,}\\/[**-**\\/\_0-9a-zA-Z]{**3**0,}$/$script,1p,domain=gu-global.com_ seems to work on all past examples I have and without false positives.

**Comment by otksm** [comment]
@Yuki2718 I spotted a new pattern [here](https://web.archive.org/web/20211130055643/https://www.gu-global.com/jp/ja/) so it might be a good idea to update the filter to `/^https:\/\/www\.gu-global\.com\/[-_0-9a-zA-Z]{6,}\/[-\/_0-9a-zA-Z]{30,}$/$script,1p,domain=gu-global.com` instead.

**Comment by JobcenterTycoon** [comment]
Tracking is back on `gu-global.com`

**Comment by Yuki2718** [comment]
> Tracking is back on `gu-global.com` coming from `https://www.gu-global.com/vKYM/Gm-4/p/7/efi1JKZg/au7cJccXuG1t/BVlZblY_cBA/Um/AhEF4nQEw`

On my end it's `https://www.gu-global.com/mySse8/tGw2Dy/p8tFV/D2t0R/OS3bc/J5YaLwJG/RVhAAg/RVI/PD0suHF8` so still caught by the regex, but will adjust regex to cover that.
