### ISSUE TITLE
[Question] nicovideo.jp

### ISSUE THREAD

**Issue by otksm** [Yuki2718/adblock#41]
### URL(s) where the issue occurs (mandatory)

Full URL: https://www.nicovideo[.]jp/watch/smxxxxxxxx

### Describe the issue (mandatory)

`||nicovideo.jp/api/tkas_video_impression` blocks impression logs for sponsored/trending videos shown under "Related Videos", but users can still spot the out-of-place ad slot thanks to how unrelated the video usually is. As far as I am aware there is no way to differentiate between "normal" related videos and "sponsored" ones css-wise so I was unable to hide them cosmetically.

If you inspect the response for `https://nvapi.nicovideo.jp/v1/recommend?recipeId=video_watch_recommendation&videoId=smxxxxxxxx&site=nicovideo&_frontendId=6&_frontendVersion=0` whenever `||nicovideo.jp/api/tkas_video_impression` fires, the "sponsored" video has a `"recommendType": "tkasF"` instead of the usual `"recommendType": "recommend"`. I tried reading up on `json-prune.js` but it doesn't look like I can remove elements based on the value of a particular property. Is there anyway for me to hide this irrelevant content?

### Versions (mandatory)

- Browser and version: Firefox Desktop
- uBlock Origin version: 1.38.6 

### Filters (mandatory)

Yuki's uBlock Japanese filters

**Comment by Yuki2718** [comment]
I confirmed what you described, but I'm afraid it's probably impossible to remove them by uBO's function.
