### ISSUE TITLE
Rule files moved

### ISSUE THREAD

**Issue by spirillen** [Yuki2718/adblock#42]
Hi @Yuki2718 

This is just to inform you I have reordered how I keeps my rules in a new file-structure.

Next to this I'm considering if I should integrate both the `Squid-Proxy` and `ublockorigin-rules` into the matrix project. Do you have any thought you would share on that?

![image](https://user-images.githubusercontent.com/44526987/144749747-9feddc97-2d56-4087-963c-49105d7393f0.png)

**Comment by Yuki2718** [comment]
Hmm, is that related to my projects? TBH I have almost no idea what you're talking about.

**Comment by Yuki2718** [comment]
Can this be closed? 

> Do you have any thought you would share on that?

I have no idea what is the matrix project.

**Comment by spirillen** [comment]
Hmm thought you was using my anti-whitelist....
