### ISSUE TITLE
uniqlo.com

### ISSUE THREAD

**Issue by otksm** [Yuki2718/adblock#44]
### URL(s) where the issue occurs (mandatory)

Full URL: `https://www.uniqlo.com/jp/ja/` (and many other regions)

### Describe the issue (mandatory)

Canvas Fingerprinting. Script content is identical to the one found in #40. Note that `hk` does not follow the conventional domain pattern and the script is not present on `cn` and `kr` storefronts.

### Proposed Solution

`/^https:\/\/www\.uniqlo\.com(\.hk)*\/[-_0-9a-zA-Z]{6,}\/[-\/_0-9a-zA-Z]{30,}$/$script,1p,domain=uniqlo.com|uniqlo.com.hk`

### Versions (mandatory)

- Browser and version: Firefox Desktop
- uBlock Origin version: 1.39.2

### Filters (mandatory)

Yuki's uBlock Japanese filters

### Notes

This script is also present on many other e-commerce sites once I started looking for it. Since they will essentially follow the same pattern, do you want me to file separate issues for each site or should I just lump them into a single giant issue?

**Comment by Yuki2718** [comment]
There's already
```
! cf. https://github.com/Yuki2718/adblock/issues/40
/^https:\/\/www\.uniqlo\.com\/[a-zA-Z]{6,}\/[-\/0-9a-zA-Z]{45}$/$script,1p,domain=uniqlo.com
```
in Paranoid. The reason for Paranoid is I don't use this site so not sure about its safety, but will move to jp-filters with modification.

**Comment by JobcenterTycoon** [comment]
Looks like ipqualityscore because i see these scripts exacly on these "Join Thousands of Happy Clients" provided on their start page

**Comment by Yuki2718** [comment]
> Looks like ipqualityscore because i see these scripts exacly on these "Join Thousands of Happy Clients" provided on their start page

Yep, tho it's not blocked by the same regex. I wonder if it should be blocked given the site is exactly the ~~security~~ tracking provider.
