### ISSUE TITLE
More canvas fingerprinting

### ISSUE THREAD

**Issue by otksm** [Yuki2718/adblock#45]
### URL(s) where the issue occurs (mandatory)

See below.

### Describe the issue (mandatory)

Canvas Fingerprinting. I have decided to file these as a single issue because it's essentially the same script and I don't want to spam the issue tracker.

Note that one or two sites have a `\/[-_0-9a-zA-Z]{4,}\/` instead of `\/[-_0-9a-zA-Z]{6,}\/` because I have seen the length of first path gone as low as 4 there. I did not lower it for other sites just in case there might be false positives (not that I have seen any).

```
! https://www.ana.co.jp/
/^https:\/\/www\.ana\.co\.jp\/[-_0-9a-zA-Z]{6,}\/[-\/_0-9a-zA-Z]{30,}$/$script,1p,domain=ana.co.jp

! https://www.asos.com/
/^https:\/\/www\.asos\.com\/[-_0-9a-zA-Z]{4,}\/[-\/_0-9a-zA-Z]{30,}$/$script,1p,domain=asos.com

! https://www.comptoirdescotonniers.co.jp/
/^https:\/\/www\.comptoirdescotonniers\.co\.jp\/[-_0-9a-zA-Z]{6,}\/[-\/_0-9a-zA-Z]{30,}$/$script,1p,domain=comptoirdescotonniers.co.jp

! https://www.flypeach.com/
/^https:\/\/www\.flypeach\.com\/[-_0-9a-zA-Z]{6,}\/[-\/_0-9a-zA-Z]{30,}$/$script,1p,domain=flypeach.com

! https://www.helmutlang.com/
/^https:\/\/www\.helmutlang\.com\/[-_0-9a-zA-Z]{6,}\/[-\/_0-9a-zA-Z]{30,}$/$script,1p,domain=helmutlang.com

! https://www2.hm.com/ja_jp/index.html
/^https:\/\/www2\.hm\.com\/[-_0-9a-zA-Z]{6,}\/[-\/_0-9a-zA-Z]{30,}$/$script,1p,domain=hm.com

! https://www.jal.co.jp/jp/ja/
/^https:\/\/www\.jal\.co\.jp\/[-_0-9a-zA-Z]{6,}\/[-\/_0-9a-zA-Z]{30,}$/$script,1p,domain=jal.co.jp

! https://www.jetstar.com/jp/ja/home
/^https:\/\/www\.jetstar\.com\/[-_0-9a-zA-Z]{6,}\/[-\/_0-9a-zA-Z]{30,}$/$script,1p,domain=jetstar.com

! https://www.theory.co.jp/
/^https:\/\/www\.theory\.co\.jp\/[-_0-9a-zA-Z]{6,}\/[-\/_0-9a-zA-Z]{30,}$/$script,1p,domain=theory.co.jp

! https://www.zara.com/jp/ (via https://www.zara.com/)
/^https:\/\/www\.zara\.(com|cn)\/[-_0-9a-zA-Z]{4,}\/[-\/_0-9a-zA-Z]{30,}$/$script,1p,domain=zara.com|zara.cn

! https://zozo.jp/
/^https:\/\/zozo\.jp\/[-_0-9a-zA-Z]{6,}\/[-\/_0-9a-zA-Z]{30,}$/$script,1p,domain=zozo.jp


! https://github.com/Yuki2718/adblock/issues/44#issuecomment-987118029

! https://www.aa.com/homePage.do?locale=en_US
/^https:\/\/www\.aa\.com\/[-_0-9a-zA-Z]{6,}\/[-\/_0-9a-zA-Z]{30,}$/$script,1p,domain=aa.com

! https://www.americanairlines.jp/
/^https:\/\/www\.americanairlines\.jp\/[-_0-9a-zA-Z]{6,}\/[-\/_0-9a-zA-Z]{30,}$/$script,1p,domain=americanairlines.jp

! https://www.costco.com/
/^https:\/\/www\.costco\.com\/[-_0-9a-zA-Z]{6,}\/[-\/_0-9a-zA-Z]{30,}$/$script,1p,domain=costco.com

! https://www.ibm.com/
/^https:\/\/www\.ibm\.com\/[-_0-9a-zA-Z]{6,}\/[-\/_0-9a-zA-Z]{30,}$/$script,1p,domain=ibm.com

! https://www.santanderbank.com/
/^https:\/\/www\.santanderbank\.com\/[-_0-9a-zA-Z]{6,}\/[-\/_0-9a-zA-Z]{30,}$/$script,1p,domain=santanderbank.com

! https://www.shopdisney.com/
! https://www.shopdisney.co.uk/
/^https:\/\/www\.shopdisney\.(com|co\.uk)\/[-_0-9a-zA-Z]{6,}\/[-\/_0-9a-zA-Z]{30,}$/$script,1p,domain=shopdisney.com|shopdisney.co.uk
```

### Versions (mandatory)

- Browser and version: Firefox Desktop
- uBlock Origin version: 1.39.2

### Filters (mandatory)

Yuki's uBlock Japanese filters

### Notes

I can confirm that the randomized path always ends with a capital `B` or `C` (at least for now). If we are not going to use one filter for each site then it might be worth trying something like `/[-_0-9a-zA-Z]{6,}\/[-\/_0-9a-zA-Z]{29,}[BC]$/$script,1p,match-case,domain=` to minimize the possibility of false positives.

**Comment by Yuki2718** [comment]
Thanks for reporting. I'll check tomorrow as these are  a lot and will take time.

**Comment by Yuki2718** [comment]
These are really many sites and all are kinda sensitive site. Given what @JobcenterTycoon [said](https://github.com/Yuki2718/adblock/issues/44#issuecomment-987118029) in another issue which seems to be true, I'll put them in Paranoid. This is what I call "Fingerprint for the sake of security", nowadays very common, and blocking them occasionary causes serious issue e.g. https://github.com/easylist/easylist/pull/6075#issuecomment-742078561 . I'll keep gu-global.com and uniqlo.com in main list though, as these are already added to uBlock Privacy and AGTPF - many more use base so hopefully any trouble will be reported.

**Comment by Yuki2718** [comment]
`header=etag` will be safer and thus maybe we should reconsider to add to uBlock filters - Privacy. @JobcenterTycoon what do you think?

**Comment by Yuki2718** [comment]
Unfortunately, `/\/[-_0-9a-zA-Z]{4,}\/[-\/_0-9a-zA-Z]{25,}$/$script,strict1p` can not be made tokenizable.

**Comment by JobcenterTycoon** [comment]
Im prefer the safer way

**Comment by Yuki2718** [comment]
`$header` is currently not default-enabled. I thought we had internal discussion about AkamaiBM and probably have to discuss something for the option to be enabled. Also I'm not sure if removing etag is enough or not, and @otksm the etag value now I see on these sites is `8409041ac476a7510c102db57c136d81cff01ee43c3f229561f4cfa05eb78940` - it may not be very stable?

**Comment by Yuki2718** [comment]
The regex works, being untokinizable means the number of such filters propotionally affects performance and there's no more mitigation than specifying as much (`$script,strict1p`). And there's still concern of false positive.

**Comment by Yuki2718** [comment]
The etag value now I see on `www.net-a-porter.com/en-jp/` is `2000504ef61113a85c086866f4d548af5a3cac1c69647b9a9abc7222b6e000b7`. It's likely revolving and keep maintaining such a filter will be burden for volunteer, not to mention header filtering is currently turned off by default. The rest possibility is the regex rule but I'm not willing to add it as generic one, gorhill expressed concern of any risky generic rule in another past case and he won't be happy to add generic untokenizable regex rule. I close this for now, but if anyone find something interesting please comment on and share your findings.
