### ISSUE TITLE
OT: Regarding publicwww.com lookup

### ISSUE THREAD

**Issue by spirillen** [Yuki2718/adblock#46]
Hi @Yuki2718 

I know this is a bit controversial, but would it be possible to request you to look up
https://publicwww.com/websites/warpstorage.pro/ , as I know you have a subscription, and verify my suspicion, that this CDN should be safe to block?

It is related to https://mypdns.org/my-privacy-dns/porn-records/-/issues/1969

**Comment by Yuki2718** [comment]
Declined, the reason I have access is that I'm allowed to use AdGuard's shared premium account which has upperlimit in searches per day, I don't want to abuse given trust for anything other than what is really needed to EL/uAssets/AG/my personal needs. You should be able to two results with free acount on your search.

**Comment by spirillen** [comment]
Fair reason :smiley: 

Thanks for your time
