### ISSUE TITLE
medium_mode/static-rules.txt

### ISSUE THREAD

**Issue by spirillen** [Yuki2718/adblock#47]
Hey @Yuki2718  is it deliberately you have deleted `medium_mode/static-rules.txt` or is it a mistake?  can't find any text for it in the readme

**Comment by Yuki2718** [comment]
>  can't find any text for it in the readme

> The following lists were removed:
> - AdGuard Tracking Protection Plus
> - Placeholder Hider with no generic hiding for mobile
> - **Yuki's uBlock Static Rules**

I notified the removal at Nov. 16., though I haven't gave any name to the list... it was DandelionSprout who named the list when he registerd the list to Filterlists .com. I was not aware that you included the list, I thought it's only anti-allowlist but apparently I was wrong.

**Comment by spirillen** [comment]
Yep you can see the full list of what I do include here: https://mypdns.org/my-external-stuff/ublockorigin-rules/-/blob/master/ublockorigin-rules.template

It is to have the same filters on al my browsers regardless systems etc.
