### ISSUE TITLE
The filter title should contain unique words

### ISSUE THREAD

**Issue by 280blocker** [Yuki2718/adblock#5]
それぞれのフィルタのタイトルが一般的な用語のため、Adblockソフトに登録したときにYuki2718さんのフィルタであることがわかりにくいですし、広告ブロックソフトの純正フィルタと誤解されるおそれがあります。
固有の言葉をフィルタタイトルに入れていただけると嬉しいです。

PC版フィルタについては自分で作るのをあきらめていたので、私よりフィルタ技術に詳しい方が作ったものが公開されるのはとてもうれしいです。ありがとうございます。

**Comment by Yuki2718** [comment]
@280blocker 言われてみると確かにそうですね。HNにせよあまり自分の名前は入れたくなかったのですが、他に思いつかないのでその路線で変更しておきます。

こちらこそモバイルで長年お世話になっております。
