### ISSUE TITLE
qiita.com

### ISSUE THREAD

**Issue by otksm** [Yuki2718/adblock#50]
### URL(s) where the issue occurs (mandatory)

Full URL: Any article on `https://qiita.com`.

### Describe the issue (mandatory)

```
! Why not register and get more from Qiita?
qiita.com##.apm-Content
```

### Versions (mandatory)

- Browser and version: Firefox 95.0.2
- uBlock Origin version: 1.40.2

### Filters (mandatory)

Yuki's uBlock Japanese filters
Yuki's uBlock Japanese filters - Annoyances

**Comment by Yuki2718** [comment]
So far I can't reproduce, the popup seems to be very conditional.
