### ISSUE TITLE
Clarification for PlaceHolder list

### ISSUE THREAD

**Issue by RicoHeat** [Yuki2718/adblock#51]
Hello @Yuki2718 
I just wanted a quick clarification for list "Placeholder Hider with no generic hiding for mobile" 
You mentioned that you will no longer update that list.. Specifically for mobile.. list was updated on the 21st.. But the list doesn't have a 'mobile' tag..
Were there 2 lists originally and the one remaining is the non mobile version? 

Just a quick question.. Thanks in advance my friend 👍 and have a great day!

**Comment by Yuki2718** [comment]
Hi, there was a list named "Placeholder Hider with no generic hiding for mobile" different from "Placeholder Hider with no generic hiding" and removed from this repo. The latter is still maintained.

**Comment by RicoHeat** [comment]
> Hi, there was a list named "Placeholder Hider with no generic hiding for mobile" different from "Placeholder Hider with no generic hiding" and removed from this repo. The latter is still maintained.

@Yuki2718 Thanks for the clarification.
