### ISSUE TITLE
source.chromium.org

### ISSUE THREAD

**Issue by otksm** [Yuki2718/adblock#53]
### URL(s) where the issue occurs (mandatory)

Full URL: `https://source.chromium.org/`

### Describe the issue (mandatory)

Potential tracking? `||play.google.com/log?$redirect=noop.txt,image,media,subdocument,stylesheet,script,xmlhttprequest,other` in Adguard Tracking Protection and `||play.google.com/log?$image,xhr,redirect=noop.txt` in Yuki's uBlock Japanese filters do not cover `https://play.google.com/log` on this site. I did not check the response payload because it was blocked by uMatrix.

### Versions (mandatory)

- Browser and version: Firefox 99.0.1
- AdGuard or uBlock Origin version: uBlock Origin 1.42.4

### Filters (mandatory)

Adguard Tracking Protection
Yuki's uBlock Japanese filters

### Notes

`||play.google.com/log|$xmlhttprequest,redirect-rule=noop.txt,domain=source.chromium.org`

**Comment by Yuki2718** [comment]
This is a problematic one with potential and conditional breakage not easy to reproduce. Maybe for Paranoid.

**Comment by Yuki2718** [comment]
Blocked generically, I assumed if the "without ?" request is only used in the domain there will be not too big risk of breakage.
