### ISSUE TITLE
automaton-media.com

### ISSUE THREAD

**Issue by otksm** [Yuki2718/adblock#56]
### URL(s) where the issue occurs (mandatory)

Full URL: `https://automaton-media.com/`

### Describe the issue (mandatory)

Ads masquerading as "PR" articles.

### Versions (mandatory)

- Browser and version: Firefox Desktop
- uBlock Origin version: 1.42.4

### Filters (mandatory)

Yuki's uBlock Japanese filters

### Notes

Filters can feel a little slow at times so I used HTML filtering instead.

```
!#if env_firefox
! ピックアップ？
automaton-media.com##^.td-big-grid-meta > .td-post-category[href="https://automaton-media.com/articles/pr/"]:upward(.td-big-grid-post)
! 最新記事
automaton-media.com##^.td-module-meta-info > .td-post-category[href="https://automaton-media.com/articles/pr/"]:upward(.td-block-span12)
! PR/求人PR
automaton-media.com##^.td_block_2 > h4.block-title:has-text(PR):upward(1)
!#endif
```

**Comment by Yuki2718** [comment]
Will look tomorrow as I don't have time now.
