### ISSUE TITLE
anti-allowlist.txt

### ISSUE THREAD

**Issue by otksm** [Yuki2718/adblock#57]
### URL(s) where the issue occurs (mandatory)

N/A

### Describe the issue (mandatory)

`||play.google.com/log$important,domain=~myaccount.google.com` is probably redundant because `@@||play.google.com/log?$xmlhttprequest,domain=google.com` has been removed from EP quite some time ago (I can't find the exact commit).

### Versions (mandatory)

- Browser and version: Firefox Desktop 
- uBlock Origin version: 1.42.4 

### Filters (mandatory)

Yuki's uBlock Anti-allowlist (anti-allowlist.txt)

**Comment by Yuki2718** [comment]
That was conditional breakage which may possibly be no more problem, but in this case I'll choose safer approach. Yuki's uBlock Japanese also has an exclusion `@@||play.google.com/log?$domain=meet.google.com`.
