### ISSUE TITLE
tenki.jp 必要コンテンツが非表示になる

### ISSUE THREAD

**Issue by gontazaka** [Yuki2718/adblock#6]
フィルター：/japanese/jp-filters.txt
URL：https://tenki.jp/forecast/3/

■原因
`tenki.jp##.section-wrap:has(.OUTBRAIN)`

■対策
スコープを絞ってみるのはどうでしょうか
`tenki.jp##.section-wrap:has(>.OUTBRAIN)`

**Comment by Yuki2718** [comment]
@gontazaka 早速のご報告ありがとうございます。元々のフィルタがちょっと雑だった気もするので、
`tenki.jp##.mb20:has(> .OUTBRAIN)`
まで絞ってみたいと思います

**Comment by Yuki2718** [comment]
ダメですね、ちょっと探したらこれでは消えないものがありました。ご提案されたルールに変えます
