### ISSUE TITLE
forest.watch.impress.co.jp

### ISSUE THREAD

**Issue by stm-x** [Yuki2718/adblock#62]
### URL(s) where the issue occurs (mandatory) / 問題のURL（必須）

Full URL / 完全なURL:
 `https://forest.watch.impress.co.jp/docs/news/1426518.html`
`https://click.linksynergy.com/deeplink?id=zufrxFCTPNQ&mid=39726&murl=https://www.xbox.com/ja-jp/games/store/minecraft-java-bedrock-edition-for-pc/9nxp44l49shj`
### Describe the issue (mandatory) / 何が問題か説明してください（必須）

Not redirected to product page if Yuki's filter is enabled.
雪フィルタを有効にしている場合、商品ページにリダイレクトされない

### Screenshot(s) / スクリーンショット

<details><summary>Screenshot:</summary>

![タイトルなし1](https://user-images.githubusercontent.com/86018494/180152545-d45875fd-65b5-44bf-b540-413e05cda0d4.png)

When Enable yuki's filter

![タイトルなし](https://user-images.githubusercontent.com/86018494/180152560-f18b5fa6-4d35-449b-a6c0-c1a7c110a2f3.png)

When Disable yuki's filter
![タイトルなし2](https://user-images.githubusercontent.com/86018494/180152553-df4084fa-48d2-4c58-8271-02089e9d3b77.png)

</details>

### Versions (mandatory) / バージョン情報（必須）

- Operating system and version / OSの種類とバージョン: Windows 11
- Browser and version / ブラウザの種類とバージョン: Chrome 103.0.5060.134
- AdGuard or uBlock Origin version / AdGuardないしuBlock Originのバージョン: 1.43.0

### Filters (mandatory) / 使用フィルタ（必須）
Yuki's uBlock Japanese filters

### Notes / その他有用な情報
uBOのログを見た感じremoveparam関連のようです

**Comment by Yuki2718** [comment]
`?sharedid=$doc,removeparam,domain=msafflnk.net`ですね。今見ると過激な・・削除しておきます。
