### ISSUE TITLE
famitsu.com

### ISSUE THREAD

**Issue by otksm** [Yuki2718/adblock#65]
### URL(s) where the issue occurs (mandatory)

Full URL: `https://www.famitsu.com/search/?category=new-article`

### Describe the issue (mandatory)

Ads masquerading as promoted articles. `famitsu.com##.ad-native-campaign-leftout:upward(.l-contents-block)` should probably do but just to be on the safe side I'd propose

```
! 特設・企画
famitsu.com##.ad-native-campaign-leftout
famitsu.com##.l-contents-block:has-text(特設・企画):not(:has(>.ad-native-campaign-leftout:not(:matches-css(display:none))))
```

### Versions (mandatory)

- Browser and version: Firefox Desktop
- uBlock Origin version: 1.42.4

### Filters (mandatory)

Yuki's uBlock Japanese filters
Yuki's uBlock Japanese filters - Annoyances

**Comment by Yuki2718** [comment]
Maybe `##.search-box--category + .l-contents-block:has(.ad-native-campaign-leftout)`. I'm wondering to block in main or in Annoyances. We already block the same link so if this is blocked too most of means to see the native-ad articles will be derived from user.
