### ISSUE TITLE
ana.co.jp

### ISSUE THREAD

**Issue by otksm** [Yuki2718/adblock#66]
### URL(s) where the issue occurs (mandatory)

Full URL:  (Click on any notices at the top of) `https://www.ana.co.jp/ja/jp/`

### Describe the issue (mandatory)

`https://www.ana.co.jp/common/js/google.js` was identical to `https://www.ana.co.jp/common/js/GTMTOP.js`. The latter was already blocked in _Yuki's uBlock Japanese filters_.

### Versions (mandatory)

- Browser and version: Firefox Desktop
- uBlock Origin version: 1.42.4

### Filters (mandatory)

Yuki's uBlock Japanese filters

**Comment by Yuki2718** [comment]
Wrongly closed despite I forgot to add the rule.
