### ISSUE TITLE
this repo

### ISSUE THREAD

**Issue by otksm** [Yuki2718/adblock#67]
Hi. Just saw the news that you will soon stop maintaining your Japanese filters. Can I just say that I found your filters generally useful, and on multiple occasions they managed to cover things that were not blocked in other stock lists or even AGJPN.

Can I ask if you are just going to archive this repo or actually deleting it? Personally, I would prefer to continue using them for a while even though they might no longer be actively maintained (for reasons stated above).  If it's just the former then would it be possible to set a longer expiration time just before archiving? (Of course I can always copy all of them into My filters but that's not very feasible on mobile)

Oh and massive thanks for fixing up AGJPN shortly after that became the default JPN filter in uBO btw. Not sure it was any better than ABPJP (in a different way) at that point back then.

**Comment by Yuki2718** [comment]
The new list will include: 1. generic rules to address ads, anti-adb, or popup, 2. specific rules not added to AGJPF. For 1, as my available time is going to be limited, I have to choose only rules with high utility and being long-lived (or likely to be so). I can't even add all the rules in anti-antiadb.txt. And yes, the list will support AGMV3 and uBOL so anyway I have to minimize the number of network rules, particularly regex ones. The list will only address ads, scam/malware, and too obtrusive annoyances. Tracker and tracking parameter currently only in Yuki's JPF should be transferred to other public privacy lists. For 2, it'll mostly be rules for low-traffic sites. But to prevent people from rushing to post all those sites, I will probably accept only breakage report publicly and limit other issues to those who have GH account and contribution history either on this repo or other major ones.

**Comment by Yuki2718** [comment]
It turned out a month was not enough to tell user that the lists will be deprecated. I can't delay the deadline, but before archiving I'll add `更新終了/Deprecated` in title of all the lists to help people understand (I'm using this issue as a reminder).
