### ISSUE TITLE
Please join the blockade

### ISSUE THREAD

**Issue by e-ct** [Yuki2718/adblock#7]
Hi,
@Yuki2718 
Can you please add these to the blockade?
for tracking-plus.txt

```
/amp4ads*.js
/amp-ad*.js
/adw.js
/gpt.js
/prebid*.js
/yap-iframe.js
/yap.js
```

Thank you.

**Comment by Yuki2718** [comment]
Hi, thank you for your suggestion. Could you give me websites they're in use, though I have certainly seen some of them somewhere?

**Comment by e-ct** [comment]
Hi,
```
ettoday.net
tw.yahoo.com
```

**Comment by Yuki2718** [comment]
Both seem to be Taiwanese websites. Tracking Protection Plus' scope is limited to English websites. I keep this issue opened for a while and if you don't know English websites they're in use, I'll try to find these by myself.

**Comment by Yuki2718** [comment]
@e-ct Why closed, I haven't said I won't add them. Of note, @tofukko's filter is meant for Japanese websites so you'll probably need to provide examples of Japanese websites.

**Comment by e-ct** [comment]
Hi,
Sorry I can't find a suitable English site.

**Comment by Yuki2718** [comment]
In that case I'll search for instead of you, so please keep this opened until I conclude. It may take time as I have some other issues on other popular repositories.

**Comment by Yuki2718** [comment]
As a first step:
- `/amp4ads*.js` was found on `https://www.siliconindia.com/` as a form of `https://www.siliconindia.com/homeoutside/js/home_new_js/amp4ads-host-v0.js`, yet it's an ad-script and not a tracker, moreover already covered by an EL rule `/amp4ads-` so I'll skip it.

- `/amp-ad*.js, /adw.js, /prebid`: found on many English / international websites but the same, not a tracker and covered by EL rules.

- `/gpt.js`: a difficult case as it's a part of googletagservices or doubleclick. There may be websites named this staff differently, tho IDK if Google allows it or not - anyway often seen in case of GA. It requires some time to evaluate.

- `/yap-iframe.js` (full form: `https://s.yimg.com/av/yap/ga/yap-iframe.js`): surely an analytics not covered by other filters and apparently used by some international websites; however, couldn't spot an actual fire so far. Need more time.

- `/yap.js`: included in Mochi filter and the script is alive on International and Japanese version of Huffpost too; will be added (tho in a slightly modified form) to both Tracking Protection Plus and Japanese filters.

Please note, TPP targets only trackers or analytics not covered by described setup on the page.

**Comment by e-ct** [comment]
Hi,
If you cannot or cannot continue processing, you can just give up.

**Comment by Yuki2718** [comment]
@e-ct Ha-ha, apparently you're too hasty. In popular repositories such as EL, it's common for you to wait for days or even weeks. I noticed removing the last period in the rule I added should cover `/yap-iframe.js` too and on uBO there will be no harm by doing this. Not that sure on AG but adding `$script` will be enough to prevent possible FP. So the only thing left is `/gpt.js` but it's really difficult to search something ending with this pattern which is not doubleclick or GTS.

**Comment by Yuki2718** [comment]
I found actually `/ga/yap.js` is in EasyPrivacy and also TPP already has
`||s.yimg.com/av/yap/ga/yap.js|`.
I'll just adopt the EP rule and delete the current one. I could find some `/gpt.js` not part of GTS/DC in some international websites, but it turned out this is already covered by an EL rule `/gpt.js$script`.  I still can't find any actual firing of `/yap-iframe.js`  even on the provided links - this is certainly in inline-script at `tw.yahoo.com` but somehow not fired. I'll anyway add this, it can't harm. Now closing, thanks again @e-ct for your suggestion.
